#! /bin/bash
#  Test cases for assignment #2
#
#  There are two instances of kopy here. kopy_1 and kopy_2.
#  Both files are identical except for the buffer size used
#  to read and write while copying.
#  kopy_1 uses a buffer size of 1024 while kopy_2 is 4096.
#
#  Dummy files were created with arbitrary sizes ranging
#  from 1mB to 100mB. The contents of these files were
#  then copied over to a series of 'complete_dump_*' files.

echo "---------------------------------------------------"
echo "- Setting up dummy files for copy                 -"
echo "---------------------------------------------------"
dd if=/dev/zero of=dump_1 bs=1024k count=1;
dd if=/dev/zero of=dump_2 bs=1024k count=25;
dd if=/dev/zero of=dump_3 bs=1024k count=50;
dd if=/dev/zero of=dump_4 bs=1024k count=75;
dd if=/dev/zero of=dump_5 bs=1024k count=100;

gcc kopy_1.c -o kopy_1
gcc kopy_2.c -o kopy_2

echo
echo "---------------------------------------------------"
echo "- Running copy rate speed test (1024 byte buffer) -"
echo "---------------------------------------------------"
for i in {1..5};
do
    size_b=$(ls -als | grep "ump_$i" | awk {'print$6'});
    size_mb=$((size_b >> 20 ));
    echo Test $i
    echo "Size: $size_mb mB";
    ./kopy_1 -r -s dump_$i complete_dump_$i;
    echo
done

rm complete_dump*

echo "---------------------------------------------------"
echo "- Running copy rate speed test (4096 byte buffer) -"
echo "---------------------------------------------------"
for i in {1..5};
do
    size_b=$(ls -als | grep "ump_$i" | awk {'print$6'});
    size_mb=$((size_b >> 20 ));
    echo Test $i
    echo "Size: $size_mb mB";
    ./kopy_2 -r -s dump_$i complete_dump_$i;
    echo
done

rm *dump*
