#! /bin/bash
#Lab 1
#
#Exercise 3
#load_reduce
#
#Objectives:
#  1. Learn how to monitor a process using ps
#  2. Learn to write script programs usig ps for CPU utilisation management
#
#Author: Ian Lodovica
#Date: 10/2/2016

#send proc information to files for later reading
ps aux | awk '$1 != "USER" {print$1}' > names
sort names | uniq > uniq_list

proc_count=$(wc -l names | awk '{print$1}');
busy_process=$(ps aux | sort -k 3 -r | head -2 | tail -1);
proc_name=$(echo busy_process | awk '{print$1, $11}');
proc_cpu_max=$(echo busy_process | awk '{print$3}');
proc_cpu_id=$(echo busy_process | awk '{print$2}');
round_cpu=$(echo $proc_cpu_max | sed 's/\..$//');

echo -e "\nProcs \tUsers"

while read xuser
do
    x=$(grep "$xuser" names | wc -l)
    echo -e "$x \t $xuser"
done < uniq_list


echo;

echo Process Count: $proc_count;
echo Busiest Process: $proc_name;

if(( round_cpu >= 60)); then
    kill proc_cpu_id;
    echo $busy_process | awk '{print$2}'; 
fi

#cleanup
rm names uniq_list;
exit 0
